#include "levelDataLoaders.h"

void LoadLevel13(
    std::vector<std::unique_ptr<Block>>& blocks,
    std::vector<std::unique_ptr<Goomba>>& goombas,
    std::vector<std::unique_ptr<Koopa>>& koopas,
    std::vector<std::unique_ptr<PiranhaPlant>>& piranhaPlants,
    std::vector<FireBar>& fireBars,
    std::vector<std::unique_ptr<BowserFire>>& bowserFires,
    std::vector<Lift>& lifts,
    std::vector<Coin>& coins,
    std::vector<BackgroundProp>& levelProps,
    std::unique_ptr<CastleFlagpole>& castleFlagpole,
    bool& followCamera,
    Texture2D& spriteSheet,
    Texture2D& mushroomSheet,
    Texture2D& marioSheet,
    Texture2D& enemiesSheet,
    int tileSize
) {
    const SceneType& scene = GetSceneType(SceneKind::Underground);
    (void)goombas;
    (void)koopas;
    (void)piranhaPlants;
    (void)levelProps;
    (void)enemiesSheet;
    (void)tileSize;
    followCamera = true;

    castleFlagpole = std::make_unique<CastleFlagpole>(152.0f, 600.0f, spriteSheet, mushroomSheet, marioSheet);

    levelProps.push_back(BackgroundProp(378, 348, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(0, 390, spriteSheet, CASTLE_LAYOUT));
    levelProps.push_back(BackgroundProp(126, 138, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(756, 96, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(1428, 348, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(1554, 306, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(1890, 516, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(2100, 180, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(2394, 348, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(2772, 138, spriteSheet, MEDIUM_CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(3192, 516, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(3486, 348, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(3612, 306, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(3948, 516, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(4158, 180, spriteSheet, MEDIUM_CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(4788, 138, spriteSheet, MEDIUM_CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(5208, 516, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(5502, 348, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(5628, 306, spriteSheet, CLOUD_LAYOUT));
    levelProps.push_back(BackgroundProp(5964, 516, spriteSheet, CLOUD_LAYOUT));

    coins.emplace_back((float)(26 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(27 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(28 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(36 * TILE_SIZE), (float)(3 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(37 * TILE_SIZE), (float)(3 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    goombas.push_back(std::make_unique<Goomba>((43 * TILE_SIZE), (5 * TILE_SIZE), enemiesSheet, GetSceneType(SceneKind::Overworld)));
    goombas.push_back(std::make_unique<Goomba>((45 * TILE_SIZE), (5 * TILE_SIZE), enemiesSheet, GetSceneType(SceneKind::Overworld)));
    coins.emplace_back((float)(49 * TILE_SIZE), (float)(7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(50 * TILE_SIZE), (float)(7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    koopas.push_back(std::make_unique<Koopa>((29 * TILE_SIZE), 201, enemiesSheet, GetSceneType(SceneKind::Overworld)));
    coins.emplace_back((float)(60 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(61 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(63 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(62 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    koopas.push_back(std::make_unique<Koopa>((74 * TILE_SIZE), 285, enemiesSheet, GetSceneType(SceneKind::Overworld), true, 159, 411, 72.0f, true));
    goombas.push_back(std::make_unique<Goomba>((80 * TILE_SIZE), (7 * TILE_SIZE), enemiesSheet, GetSceneType(SceneKind::Overworld)));
    coins.emplace_back((float)(85 * TILE_SIZE), (float)(6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(86 * TILE_SIZE), (float)(6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(93 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(94 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(97 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(98 * TILE_SIZE), (float)(5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    koopas.push_back(std::make_unique<Koopa>((110 * TILE_SIZE), 285, enemiesSheet, GetSceneType(SceneKind::Overworld)));
    koopas.push_back(std::make_unique<Koopa>((114 * TILE_SIZE), 285, enemiesSheet, GetSceneType(SceneKind::Overworld), true, 159, 411, 72.0f, true));
    coins.emplace_back((float)(113 * TILE_SIZE), (float)(13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(114 * TILE_SIZE), (float)(13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(115 * TILE_SIZE), (float)(13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(120 * TILE_SIZE), (float)(6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    coins.emplace_back((float)(121 * TILE_SIZE), (float)(6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld));
    koopas.push_back(std::make_unique<Koopa>((133 * TILE_SIZE), 537, enemiesSheet, GetSceneType(SceneKind::Overworld)));

    lifts.push_back(Lift::HorizontalBounce((53 * TILE_SIZE), (7 * TILE_SIZE) + 12, 126.0f, mushroomSheet, (53 * TILE_SIZE), (55 * TILE_SIZE), 68.0f, true));
    lifts.push_back(Lift::HorizontalBounce((84 * TILE_SIZE), (9 * TILE_SIZE) + 12, 126.0f, mushroomSheet, (84 * TILE_SIZE), (90 * TILE_SIZE), 68.0f, true));
    lifts.push_back(Lift::HorizontalBounce((92 * TILE_SIZE), (10 * TILE_SIZE) + 12, 126.0f, mushroomSheet, (92 * TILE_SIZE), (98 * TILE_SIZE), 68.0f, true));
    lifts.push_back(Lift::HorizontalBounce((131 * TILE_SIZE), (7 * TILE_SIZE) + 12, 126.0f, mushroomSheet, (131 * TILE_SIZE), (137 * TILE_SIZE), 68.0f, true));

    blocks.push_back(std::make_unique<DrawTiledRect>(
        0, 600, 656, 80, spriteSheet, GetSceneType(SceneKind::Overworld).groundBlock, TILE_SIZE, TILE_SIZE, GetSceneType(SceneKind::Overworld)
    ));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((19 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((19 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((20 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((20 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((18 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((19 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((20 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((21 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((24 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((24 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((24 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((24 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((24 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((25 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((25 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((25 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((25 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((25 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((29 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((29 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((29 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((29 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((29 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((23 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((24 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((25 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((26 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((27 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((28 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((29 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((30 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((26 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((27 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((28 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((25 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((26 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((27 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((28 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((29 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((32 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((32 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((31 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((32 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((33 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((35 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((35 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((35 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((35 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((35 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((35 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((36 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((36 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((36 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((36 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((36 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((36 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((37 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((37 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((37 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((37 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((37 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((37 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((34 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((35 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((36 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((37 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((38 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((40 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((41 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((42 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((43 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((44 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((39 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((40 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((41 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((42 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((43 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((44 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((45 * TILE_SIZE), (5 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((50 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((51 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((49 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((50 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((51 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((52 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((59 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<PowerUpBlock>((59 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, mushroomSheet, "mushroom", GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((60 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((61 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((62 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((63 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((60 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((61 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((62 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((60 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((61 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((62 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((63 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((65 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((66 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((67 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((68 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((69 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((66 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((67 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((68 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((71 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((71 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((71 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((71 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((71 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((70 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((71 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((72 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((76 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((77 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((78 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((79 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((80 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((81 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((79 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((80 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((77 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((78 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((100 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((100 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((100 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((99 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((99 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((99 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((98 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((99 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((100 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((101 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((105 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((106 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((107 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((108 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((109 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((110 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((104 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((105 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((106 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((107 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((108 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((109 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((110 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((111 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((114 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((113 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((114 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((115 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((117 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((117 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((117 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((117 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((117 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((118 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((118 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((118 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((118 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((118 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((116 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((117 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((118 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((119 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopLeftBlock>((122 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((123 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidMiddleBlock>((124 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandSolidTopRightBlock>((125 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((123 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((123 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((123 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((123 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((123 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((124 * TILE_SIZE), (15 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((124 * TILE_SIZE), (14 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((124 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((124 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<IslandBackgroundBlock>((124 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<DrawTiledRect>(
        5418, 600, 1680, 84, spriteSheet, GetSceneType(SceneKind::Overworld).groundBlock, TILE_SIZE, TILE_SIZE, GetSceneType(SceneKind::Overworld)
    ));
    blocks.push_back(std::make_unique<ShinyBlock>((138 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((138 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((138 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((138 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((139 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((139 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((139 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((139 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((140 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((140 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((140 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((140 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((140 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((140 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((141 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((141 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((141 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((141 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((141 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((141 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((142 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (13 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (12 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (11 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (10 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (9 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (8 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (7 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
    blocks.push_back(std::make_unique<ShinyBlock>((143 * TILE_SIZE), (6 * TILE_SIZE) + 12, spriteSheet, GetSceneType(SceneKind::Overworld)));
}

